### ISSUE TITLE
catalog update fetches but does not checkout

### ISSUE THREAD

**Issue by SimonGreenhill** [cldf/cldfcatalog#3]
I found that running `cldfbench catupdate` pulls but doesn't checkout, so the catalog remains at the previous commit state (rather than e.g. updating to the new version of concepticon). 

I think you also need a call to `checkout`, but  then there's an issue about running into any local uncommtited changes, so not sure what the best policy is.

https://github.com/cldf/cldfcatalog/blob/f26c9ac38c1ab111a55682ae83f4ac1cb03333c3/src/cldfcatalog/repository.py#L39

**Comment by xrotwang** [comment]
This behaviour was intentional. The idea behind the `Catalog` class is exactly that you can use your standard, working clone of a catalog repository, and only checking out release tags on demand.

So to use a particular release tag, you'd run `cldfbench catupdate` to make sure all tags are available locally, followed by `with Catalog(..., tag='...')` to checkout the desired tag temporarily.
Checking out `HEAD` otoh is something you'd do "by hand".

Does this make sense?

**Comment by SimonGreenhill** [comment]
Ok, but I was expecting to update to the latest released. Will keep that in mind.

**Comment by xrotwang** [comment]
@SimonGreenhill I'll add a bit of info to the docstring of `catupdate`.
